### ISSUE TITLE
Generating additionalProperties of a schema

### ISSUE THREAD

**Issue by LorenzHW** [LorenzHW/gnostic-grpc#3]
#### Problem description 

`additionalProperties` are currently not reflected inside the generated .proto. Considering the following OpenAPI definition, an empty message is currently generated for the response. 

    
    /testResponseAdditionalProperties:
        get:
          operationId: testResponseAdditionalProperties
          responses:
            '200':
              description: successful operation
              content:
                application/json:
                  schema:
                    type: object
                    additionalProperties:
                      type: integer
                      format: int32

What would be a proper way to generate additionalProperties inside .proto?

**Comment by noahdietz** [comment]
Based on the discussion on [swagger.io](https://swagger.io/docs/specification/data-models/dictionaries/), we might consider generating them as a protobuf [map](https://developers.google.com/protocol-buffers/docs/proto3#maps) field.

However, this might be a tad weird/break the contract because the generated type would have an extra level of depth. Example: `response.GetFieldThatsAMap().Get("key")` rather than `response.Get("key")` like a "dictionary".

The nature of protobuf makes it hard to have "free form" objects.

**Comment by LorenzHW** [comment]
Thanks Noah. I implemented it accordingly.

@noahdietz if we have `additionalProperties` with type `array` [(see](https://github.com/LorenzHW/gnostic-protoc-generator/blob/a8226b677ded744a5a1069604a8d0af13fa9a7a6/generator/testfiles/other.yaml#L47)), it gets generated like [this](https://github.com/LorenzHW/gnostic-protoc-generator/blob/a8226b677ded744a5a1069604a8d0af13fa9a7a6/generator/testfiles/goldstandard/other.proto#L30), because we can't do something like `map<string, repeated int32> ok = 1;` If that is ok, I would close this issue.

**Comment by noahdietz** [comment]
This is a little tougher. A `google.protobuf.Any` requires an actual `Message` type to still be associated with it. See the [documentation](https://developers.google.com/protocol-buffers/docs/proto3#any) where it states:

> The Any message type lets you use messages as embedded types without having their .proto definition. An Any contains an arbitrary serialized message as bytes, along with a URL that acts as a globally unique identifier for and resolves to that message's type

An OAS array is not the same as a protobuf Message, arrays can only be used in protobuf when contained as a field in a Message. Thus, we wouldn't be able to deserialize the Any bytes into a corresponding type.

I don't think this will work, but to address that we'd **add** a `Message` type of our own to wrap the response in. For example:

```protobuf
message TestAdditionalPropertiesArrayResponsesSet {
  repeated int32 items = 1;
}

message TestAdditionalPropertiesArrayResponses {
  map<string, TestAdditionalPropertiesArrayResponsesSet> ok = 1;
}
```

Again I don't think this will work because it is fundamentally different from the JSON representation.

This specific combination might be one that we cannot support. It is very specific and I'm OK with not supporting it until someone opens an issue for it or we can supply an example of it being used in the wild.

WDYT?

**Comment by LorenzHW** [comment]
Ok I see. So I think the best thing to do at this point is to warn the user that an array inside `additionalProperties` won't be represented inside the proto definition. And if someone opens an issue about this, we can implement it accordingly.

**Comment by noahdietz** [comment]
Agreed!

**Comment by LorenzHW** [comment]
[Closed](https://github.com/LorenzHW/gnostic-grpc/commit/e39c1789ba478702172821093522eab10fe33cb4) for now.
